### ISSUE TITLE
Integrating phonemes

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#10]
I know that Phonemes are a weird topic:
- not much used in OSM
- few open source implementations that process them well as audio

Still, a hot topic for doing really good voice guidance. How would we integrate them? Do we need phonemes for instructions as well, or only for street names?
- **Phonemes for instructions** They could become their own language to integrate, thus we'd have spoken language and phoneme scheme combinations
- **Phonemes for streets** These comes from OSRM and is already implemented as the `pronunciation` property for street names. They'd just be put into the instructions string then, so this would be an easy options to the instruction logic if it should look for `pronunciation`s or not.

**Comment by daniel-j-h** [comment]
> or only for street names?

Edge-Case rotaries: https://github.com/Project-OSRM/osrm-backend/pull/2870#issuecomment-245293688

**Comment by hdaymon** [comment]
Issue moved to [mapbox/directions-voice-instructions #47](https://github.com/mapbox/directions-voice-instructions/issues/47) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mcwhittemore** [comment]
While this field exists, there has been very little support for it in OSM. Until we have better coverage, I'm going to close this ticket.

**Comment by 1ec5** [comment]
Indeed, no roads in OpenStreetMap were tagged with `name:pronunciation` [until today](http://www.openstreetmap.org/changeset/52015885). Regardless, it makes more sense for clients of this library to add in the pronunciations. For example, mapbox/MapboxDirections.swift#78 would make it easy for the iOS navigation SDK to add a pronunciation hint in OSRM Text Instructions for Swift’s callback:

https://github.com/mapbox/mapbox-navigation-ios/blob/9b28e2dc65ac98ef1f9ff3c9351d8b6e6def1410/MapboxCoreNavigation/RouteStep.swift#L46
