### ISSUE TITLE
Use lower-case language codes everywhere

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#109]
We currently have `zh-Hans` which may result in confusion when people use `zh-hans` instead. Let's eliminate this source of confusion:

- [ ] Make sure all language codes in https://github.com/Project-OSRM/osrm-text-instructions/blob/145f4f3064ab3aaa06b9704c3a96e0e5e173051a/languages.js#L16-L27 are lower-case
  - change `zh-Hans` to `zh-hans`
  - write a test that fails if a non-lowercase character is added
- [ ] Make `compile(language)` accept any-cased language codes by lower-casing the input code (and have a test for this)

**Comment by 1ec5** [comment]
`zh-Hans` is the IETF/ISO standard. For interoperability with client platforms and consistency with server APIs, the Directions API should at least require the use of `zh-Hans`, but it would also be reasonable for it to accept `zh-hans` and normalize it to `zh-Hans`.

**Comment by freenerd** [comment]
@1ec5 agreed. We want to make `compile(language)` accept any-cased language codes, so that clients like Mapbox Directions API do not have to care about language code capitalisation. The easiest implementation of this is to lower-case the internal representation of language codes.

**Comment by 1ec5** [comment]
OK. Unfortunately, OSRM Text Instructions for Swift will have to add special logic to recapitalize `Hans`, since iOS matches the folder name to the system locale identifier with case sensitivity.

**Comment by freenerd** [comment]
I think we may not actually want to do this in osrm-text-instructions. I believe that language code sanitation and fallbacks are a downstream concern. Implementors should figure out which language codes to use and how to bridge between user input and what osrm-text-instructions supports.

For the concern of accepting any-case language codes, we used code similar to this:

```js 
var codes = {};
supportedCodes.forEach((code) => {
    codes[code.toLowerCase()] = code;
});
var code = codes[userCode.toLowerCase()];
osrmTextInstructions.compile(code, step);
```

I'll close this, please reopen if disagree.
