### ISSUE TITLE
Split arrival instruction into counting and non-counting

### ISSUE THREAD

**Issue by patjouk** [Project-OSRM/osrm-text-instructions#110]
Reviewing the French translation, I saw one thing that doesn't sound French but I couldn't fix it:

`You have arrived at your destination`: there's no way to remove "votre (your)" in the French translation [right now](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L53-L78). You would say "Vous êtes arrivés à votre seconde destination (you arrived at your second destination)" but  "Vous êtes arrivés à destination (you arrived at your destination)".

One solution could be to have a distinct string for 'You arrived", but without the number.

**Comment by yuryleb** [comment]
This is also good for Russian :wink: It's really better to have one string for main/final destination and another for all intermediate ones.

**Comment by freenerd** [comment]
Splitting counting arrival instructions and non-counting instructions into separate translatable strings makes sense to me.

The design may be like this then:

```json
{
        "arrive": {
            "default": {
                "default": "You have arrived at your destination"
            }
        },
        "arrive_counting": {
            "default": {
                "default": "You have arrived at your {nth} destination"
            }
     }
}
```

I'll change the title of this ticket accordingly.

@bsudekum is this something you'd want to look into as part of #111?

**Comment by bsudekum** [comment]
@freenerd let's split this out from #111

**Comment by patjouk** [comment]
Closing this issue. Please, create another one if you want to work on this.
