### ISSUE TITLE
Implement Support for Exit Numbers

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-text-instructions#114]
With https://github.com/Project-OSRM/osrm-backend/pull/4215/files osrm will have a new `exits` property in the `RouteStep` (next to destinations, pronunciations, ...).

We need to adapt the instructions to this new feature.

The primary use-case for exit numbers / exit names is for example the US where exits are numbered sequentially and are crucial for highway navigation. Here is an example:
- https://github.com/Project-OSRM/osrm-backend/blob/2bd7252e82e3a0f8ce854ecf5304c9e731c71d8b/features/guidance/exit-numbers-names.feature#L75-L98
- http://www.openstreetmap.org/way/417524818#map=16/37.3877/-121.9776

Where we should announce taking the ramp similar to:

    Take exit 393 towards Great America Parkway, Bowers Avenue

cc @freenerd @willwhite

**Comment by 1ec5** [comment]
Tracking a Swift port in Project-OSRM/osrm-text-instructions.swift#25.
