### ISSUE TITLE
Choose `destination` based on up-coming steps.

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-text-instructions#115]
Porting this over from https://github.com/Project-OSRM/osrm-backend/issues/3258

The expected behavior for [this route](http://map.project-osrm.org/?z=18&center=37.827247%2C-122.285500&loc=37.826353%2C-122.288518&loc=37.827879%2C-122.281737&hl=en&alt=0) would be the following instructions:

- `Take the ramp on the left towards San Pablo Avenue. `
- `Keep right at the fork toward San Pablo Avenue.`

However for the first instruction we will see: 

- `Take the ramp on the left towards MacArther Boulevard. `
- `Keep right at the fork toward San Pablo Avenue.`

The API response form OSRM however correctly marks the first as `MacArther Boulevard, San Pablo Avenue` and the second as `San Pablo Avenue`. It simply chooses the wrong one.

We need to determine how long the look ahead here would need to be. One instruction before and after would already be a good start I think.

**Comment by 1ec5** [comment]
Duplicate of #30?

**Comment by TheMarex** [comment]
@1ec5 Good find, closing this as duplicate.
