### ISSUE TITLE
German: rename ramps to Auffahrt/Ausfahrt

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#118]
Breaking out from https://github.com/Project-OSRM/osrm-text-instructions/pull/116/files/da902d902e59137a819c349758698f90f03fa3ff#r125589780

We might want to rename `Rampe` to `Auffahrt` and `Ausfahrt`. Only thing I wonder about is if `on_ramp` and `off_ramp` will always only be used in that context, or are there other cases? `motorway_link` [seems to be correctly identified](http://map.project-osrm.org/?z=15&center=52.280565%2C12.913227&loc=52.278504%2C12.912583&loc=52.298192%2C12.900524&hl=de&alt=0) as `off_ramp`, so we are fine there. Any other cases?

/cc @daniel-j-h @MoKob

**Comment by MoKob** [comment]
@freenerd I think we could consider using `ramp` types on trunks as well (not sure if we already do). Either way we should be able to always identify off/on correctly based on the origin type of the turn (e.g. `non-motorway` to `motorway_link` is always an `on-ramp`, `motorway` -> `motorway_link` an off ramp)

**Comment by freenerd** [comment]
@MoKob can you open an osrm-backend ticket for that?

**Comment by MoKob** [comment]
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/guidance.lua#L31-L36 trunk links are already considered as off-ramps

**Comment by freenerd** [comment]
Fixed in #122
