### ISSUE TITLE
Use relations parsed from OSRM from to include cardinal direction in instructions

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#119]
An instruction to continue on a freeway or expressway in North America should pair the route number (ref) with a cardinal direction, where available.

At many freeway junctions, especially [cloverleaf interchanges](https://en.wikipedia.org/wiki/Cloverleaf_interchange), there are separate exits leading to opposite directions on the same road. Guide signage and [reassurance markers](https://en.wikipedia.org/wiki/Reassurance_marker) usually display the cardinal direction above or below the route shield to help the driver distinguish between e.g. eastbound and westbound.

Because the signposted cardinal directions often don’t correspond to the actual direction of travel, the cardinal directions must be entered into OpenStreetMap but can’t be synthesized automatically. OpenStreetMap currently encodes cardinal directions in two ways:

* The `highway=motorway_link` way leading to the freeway or expressway [is tagged](https://wiki.openstreetmap.org/wiki/Exit_Info#Freeway_entrance) e.g. `destination:ref=I 15 North`. OSRM and OSRM Text Instructions correctly preserve the directional suffix, although the `ref` field is entirely unstructured due to Project-OSRM/osrm-backend#482, Project-OSRM/osrm-backend#3329, Project-OSRM/osrm-backend#3304, and the tagging scheme in the first place.
* The `highway=motorway` ways themselves are members of `route=road` relations. A relation member has a `role` in that relation; the `highway=motorway` ways have `role`s of `north`, `south`, `east`, or `west`. (Less commonly, the relation itself is tagged e.g. `direction=east` if it’s used only for the freeway’s eastbound direction.) OSRM would need to read the relation `role` in order to correctly indicate the cardinal direction in an instruction like “Continue on I-880 North”, since no highway ramp is involved in that case. Supporting route relations is tracked in Project-OSRM/osrm-backend#482.

In practice, we’re in a decent spot with highway ramps, even if the tagging scheme isn’t especially robust. This issue tracks getting cardinal directions into continue instructions via route relations. See [this wiki page](https://wiki.openstreetmap.org/wiki/Highway_Directions_In_The_United_States) for more details on cardinal direction tagging in OSM.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/291#issuecomment-310148579
/cc @ericrwolfe @willwhite @danpat @TheMarex @freenerd

**Comment by 1ec5** [comment]
@willwhite pointed out [this example](http://www.openstreetmap.org/way/50511177) where a freeway begins at an at-grade intersection. This situation is relatively rare in the U.S., but it’s worth getting right as well.

**Comment by 1ec5** [comment]
> The `highway=motorway_link` way leading to the freeway or expressway [is tagged](https://wiki.openstreetmap.org/wiki/Exit_Info#Freeway_entrance) e.g. `destination:ref=I 15 North`.

Note that the cardinal directions are given in English in the United States and most of Canada, [in French](https://www.openstreetmap.org/way/40662135) in Québec and New Brunswick, and [in Spanish](http://www.openstreetmap.org/way/22218363) in Puerto Rico. I’m unaware of any other languages being used in `destination:ref` tags, as these are the three main languages spoken in jurisdictions that conform to the MUTCD.

**Comment by 1ec5** [comment]
Project-OSRM/osrm-backend#4434 sketches out what cardinal directions could look like via route relation support in OSRM.

**Comment by 1ec5** [comment]
For the second case that requires relation support, it would be tricky to use way `ref`s for the route numbers in conjunction with relation `role`s or `direction` tags for the cardinal directions, since the former is intended to be human-readable while the latter is intended to be machine readable. One way this plays out is that simply appending a relation’s `direction` onto a member way’s `ref` will give incorrect results for many [route concurrencies](https://wiki.openstreetmap.org/wiki/Highway_Directions_In_The_United_States#Concurrent_routes).

For example, the following road is simultaneously part of US 29 North, US 460 East, and US 501 South. [The way](http://www.openstreetmap.org/way/39784790) is tagged `ref=US 29;US 460;US 501`, and its relation roles are `north`, `east`, and `south`, respectively. However, there’s nothing in the OSM data that explicitly puts those relations in the same order as the way `ref`, so Project-OSRM/osrm-backend#4434 mentions that we may need to match up relations with way `ref` components ourselves if we’re to continue to use the way `ref` tag at all.

[![US 29 North / US 460 East / US 501 South](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Wrong-way_concurrency_in_Lynchburg%2C_Virginia.jpg/640px-Wrong-way_concurrency_in_Lynchburg%2C_Virginia.jpg)](https://commons.wikimedia.org/wiki/File:Wrong-way_concurrency_in_Lynchburg,_Virginia.jpg)

Wrong-way concurrencies are fairly common in the U.S. Just counting relation roles and not `direction` tags (which would cause Overpass to time out) in several states:

* [620 affected ways](http://overpass-turbo.eu/s/ryn) in Ohio
* [509 ways](http://overpass-turbo.eu/s/ryo) in Indiana
* [456 ways](http://overpass-turbo.eu/s/ryc) in Tennessee
* [407 ways](http://overpass-turbo.eu/s/ry6) in Virginia
* [323 ways](http://overpass-turbo.eu/s/rym) in Missouri
* [276 ways](http://overpass-turbo.eu/s/ry8) in Georgia
* [115 ways](http://overpass-turbo.eu/s/ryq) in Utah

**Comment by hdaymon** [comment]
@1ec5 Cardinal directions now appear in text and voice instructions - is there anything additional needed to close this ticket?

e.g. https://hey.mapbox.com/binnacle/#11.8/39.74731/-104.99581/0.0/39.80485/-104.98362/39.68485/-105.00346

**Comment by 1ec5** [comment]
To my knowledge, the only things missing are:

1. Supporting French and Spanish cardinal directions in regions that are signposted in those languages: https://github.com/Project-OSRM/osrm-text-instructions/issues/119#issuecomment-324279884
1. Cleaning up route relation tags in OpenStreetMap so that OSRM can determine the cardinal direction more reliably

Both these tasks are being tracked in other repositories, so I’m closing this issue. Of the comments here, https://github.com/Project-OSRM/osrm-text-instructions/issues/119#issuecomment-328053084 is worth bookmarking for future reference.
