### ISSUE TITLE
Remove .js from repo name

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#12]
I think `osrm-text-instructions.js` is misleading, since we ideally want this to be used by non-js projects as well.

@MoKob can you rename this repo name to `osrm-text-instructions`?

@bsudekum headsup for change of git remote.

**Comment by freenerd** [comment]
```
git remote rm origin
git remote add origin git@github.com:Project-OSRM/osrm-text-instructions.git
```

**Comment by bsudekum** [comment]
But isn't this project JS specifically. Wouldn't the swift derivative live under `osrm-text-instructions.swift`?

**Comment by 1ec5** [comment]
I think the original idea was a language-agnostic repository containing nothing but data, in which case there would be no need for a separate Swift repository. As things stand, there's still a bit of logic in JavaScript. Medium-term, I think we should work to eliminate that logic using a templating language of some sort. If we need a Swift port of that logic in the meantime, we can put a Swift file right alongside the JS file in this repository, right?

**Comment by bsudekum** [comment]
Totally agree on reducing JS logic. However, I'm not sure what we can do with https://github.com/Project-OSRM/osrm-text-instructions/blob/master/lib/use-lane.js

>  If we need a Swift port of that logic in the meantime, we can put a Swift file right alongside the JS file in this repository, right?

It seems a little strange to npm install the project and end up with no-op swift code on your system.

**Comment by 1ec5** [comment]
The logic in use-lane.js could be simplified a bit in Swift using switch patterns. Even a library with the current amount of code makes little sense on iOS, where there's a higher bar for splitting off a dependency.

The main advantages of a data library shared between languages are less effort to keep data in sync and reduced load for translators. Once we open this repository to additional human languages, the kind of string manipulation seen throughout use-lane.js will have to go away anyways.
