### ISSUE TITLE
Arrival instruction should name the waypoint

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#134]
For an arrival instruction, this library says “You have arrived at the destination”. Instead of a generic “the destination”, the instruction should say the waypoint’s name, like “You have arrived at White House”.

Unfortunately, OSRM generally gives the associated street as the waypoint’s name, which would cause the instruction to mislead, e.g., “You have arrived at Pennsylvania Avenue” even though the user has been traveling on Pennsylvania Avenue since the beginning of the previous step. Fortunately, the developer can modify the waypoint’s name before passing the route step object into this library. (This is also true in Swift: MapboxDirections.swift persists the waypoint name provided in the original request.)

While we’re at it, it would be nice to change the tense from the present perfect (“You have arrived at”) to the imperative (“Arrive at”): #61.

/ref mapbox/mapbox-navigation-ios#419 mapbox/mapbox-navigation-ios#422
/cc @bsudekum

**Comment by 1ec5** [comment]
To be clear, the step’s name is the waypoint name, so we won’t need to introduce any additional inputs.

**Comment by hdaymon** [comment]
Need to verify how we want to do this.

**Comment by 1ec5** [comment]
> Fortunately, the developer can modify the waypoint’s name before passing the route step object into this library.

Note that the developer can technically get the name from any source they want, whether OpenStreetMap, the Mapbox Geocoding API, or a hard-coded string literal.

**Comment by hdaymon** [comment]
From @1ec5 

> this is something that is very doable as long as OSRMTI runs on the client side. If we do this on the server side, then api-directions needs to do some postprocessing of what it gets from OSRM. Specifically, it needs to ignore whatever OSRM names the waypoint in favor of what it was named in the URL query parameter.
> 
> [11:32] 
> But that query parameter’s value comes from our Geocoding API in the case of Voyage and other clients.
> 
> [11:33] 
> This treads kind of close to the discussion about adding geocoding capabilities to the Directions API, which has always ended in :no_good:. That’s a non-issue when everything stays on the client side, b/c the POI name gets inserted at the last possible moment, right before sending off to the text-to-speech engine. 
>

**Comment by 1ec5** [comment]
Fixed in #184.
