### ISSUE TITLE
Destinations with refs are parsed inconsistently

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#135]
[This line](https://github.com/Project-OSRM/osrm-text-instructions/blob/bdf31a49565e76db76a338f05913087c2d99b9db/index.js#L185) assumes that a step’s `destination` is a comma-separated list, but it can also take the form `Ref1, Ref2: Destination1, Destination2`. So there’s inconsistent behavior around destinations:

* [`I 71 North, US 50 East: Columbus`](http://map.project-osrm.org/?z=16&center=39.100176%2C-84.515848&loc=39.109551%2C-84.532821&loc=39.098111%2C-84.513016&hl=en&alt=0) produces “towards I 71 North” but should produce “towards I 71 North: Columbus”
* [`I 471 South: Newport, KY`](http://map.project-osrm.org/?z=17&center=39.102374%2C-84.500570&loc=39.098261%2C-84.509604&loc=39.101791%2C-84.497437&hl=en&alt=0) produces “towards I 471 South: Newport” (but see Project-OSRM/osrm-backend#3329)

/ref Project-OSRM/osrm-text-instructions.swift#31
/cc @bsudekum

**Comment by hdaymon** [comment]
Need to find out how common this problem is and do more research to find out what combinations we receive from OSRM. May need changes upstream.

**Comment by 1ec5** [comment]
#197 fixes this issue.
