### ISSUE TITLE
Rotary instructions have extra 'default' sub-node?

### ISSUE THREAD

**Issue by yuryleb** [Project-OSRM/osrm-text-instructions#166]
Please look at strings for ['rotary' group](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L349-L372), it seems to have extra 'default' node instead of 'on ramp' before and 'roundabout' after.
So the key to default rotary instruction looks as `content.v5.rotary.default.default.default` instead of, say, `content.v5.roundabout.default.default`.

Is it by design?

**Comment by mcwhittemore** [comment]
oh, @yuryleb that is weird, @1ec5 any back story here that we should know about?

**Comment by 1ec5** [comment]
The structure for the `rotary`, `roundabout`, and `roundabout turn` sections looks like this:

* Maneuver type: `rotary`
  * Maneuver modifier: `default`, because these strings don’t differentiate between whether you turn left or right to enter the rotary
    * Instruction variant: `name` or `destination` if those fields are supplied, otherwise `default`

**Comment by yuryleb** [comment]
So this really looks by design and works, I checked on local frontend instance.
