### ISSUE TITLE
Add a "Head {direction} on {way_name} for {distance}" phrase

### ISSUE THREAD

**Issue by mcwhittemore** [Project-OSRM/osrm-text-instructions#172]
When giving a direction like `Continue on 16th street` or `Head south on St James Boulevard` it would be nice to optionally add on the distance. We can currently do this for the [continue](https://github.com/Project-OSRM/osrm-text-instructions/blob/7baf2ec6c9770f65bdd8b39f21cbf4caa88b1553/languages/translations/en.json#L97) but it would be nice to be able do this departures as well.

**Comment by 1ec5** [comment]
OSRMTI never uses this string directly, but you could get the translated string out of the JSON file and do the token substitution on your own using `tokenize()`.
