### ISSUE TITLE
Remove traffic circle names from the roundabout and rotary instructions

### ISSUE THREAD

**Issue by mcwhittemore** [Project-OSRM/osrm-text-instructions#173]
This is superfluous information most of the time as roundabouts and rotaries are visually obvious things. We should simply sat `at the traffic circle, take the 1st exit` rather than `At {name}`, take the 1st exit`

**Comment by daniel-j-h** [comment]
What's the use-case for not passing through information from the backend here?

At least in Germany there are lots of rotaries you really want to announce by their names e.g. 

- [Grosser Stern](https://www.openstreetmap.org/#map=18/52.51446/13.34982)
- [Theodor-Heuss Platz](https://www.openstreetmap.org/#map=18/52.50970/13.27323)

whic are well-known and even tram and underground stations there are called by the rotary's name.

**Comment by MoKob** [comment]
I would also like to add, that the places not necessarily are visually obvious: Two examples here. One of which is currently tagged with `junction=roundabout`, the other isn't. It isn't necessarily highly obvious, that this is a traffic circle. Names, as @daniel-j-h already mentioned can be far more obvious, based on train stations and similar.

<img width="717" alt="screen shot 2017-10-12 at 09 52 46" src="https://user-images.githubusercontent.com/12932279/31485258-830c3be6-af33-11e7-9e36-1863d3f460f7.png">

<img width="711" alt="screen shot 2017-10-12 at 09 54 16" src="https://user-images.githubusercontent.com/12932279/31485259-8823e9d0-af33-11e7-879c-8e694a1235a1.png">

**Comment by mcwhittemore** [comment]
So, talking this over with @MoKob a bit offline, I think I can force the step to use [roundabout.exit.default](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L376) when using OSRM Text Instructions to make mp3s.

**Comment by mcwhittemore** [comment]
This has been done for english, if other languages want to follow suite, they can via transifex.
