### ISSUE TITLE
Rename traffic circles to roundabouts

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#188]
#179 replaced occurrences of “roundabout” with “traffic circle” in the English strings. I think we should consider returning to “roundabout” for the following reasons:

* “Roundabout” is the generally recognized term outside the United States, modulo some local color as seen in https://github.com/Project-OSRM/osrm-text-instructions/pull/179#issuecomment-338125356. We don’t want to have to maintain separate `en-GB`, `en-AU`, `en-NZ`, etc. localizations just for this one word (although I wouldn’t be opposed to starting more localizations for other reasons).
* In the United States, especially outside the Northeast, “roundabout” has achieved better recognition than “traffic circle” as a standard road feature. It’s difficult to come up with an 🍎↔🍏 comparison, because “roundabout” is also an unrelated adjective, but [“roundabout” as a noun](https://www.google.com/search?tbm=nws&q="roundabout+at"+location%3A"United+States") appears about 21 times as often as [“traffic circle”](https://www.google.com/search?tbm=nws&q=%22traffic+circle+at%22+location%3A%22United+States%22) in recent U.S. news articles.
* In the United States, “traffic circle” can [imply](https://www.fhwa.dot.gov/publications/research/safety/00067/000671.pdf) that traffic entering the junction has the right-of-way, which is only the case for the junctions OSRM calls “rotaries”. I would agree with leaving the `rotary` instructions with “traffic circle” for correctness’ sake.

Some arguments have been put forth in favor of “traffic circle”:

* For users who have yet to encounter a roundabout, the term “traffic circle” is more descriptive.
  * I would contend that the number of drivers who are unfamiliar with how to navigate a roundabout far exceeds the number of drivers who are unfamiliar with the concept in the first place.
* Google Maps says “traffic circle” [in the U.S.](https://www.google.com/maps/dir/39.3665131,-84.3206929/39.3651732,-84.3192072/@39.3663487,-84.3210892,17z/am=t/data=!4m6!4m5!3e0!6m3!1i0!2i0!3i1), [including for the traffic calming device](https://www.google.com/maps/dir/37.3539206,-121.8951318/841-801+N+7th+St,+San+Jose,+CA+95112/@37.3539106,-121.8969579,17z/am=t/data=!4m13!4m12!1m0!1m5!1m1!1s0x808fcc87327972a5:0x47b1bc438c9ed96e!2m2!1d-121.8958173!2d37.354802!3e0!6m3!1i0!2i0!3i0) that takes up the same space as a standard intersection. (They say “roundabout” [in the UK](https://www.google.com/maps/dir/51.5624299,-1.7730783/16-10+Shrivenham+Rd,+Swindon+SN1,+UK/@51.5626473,-1.7742531,16z/am=t/data=!4m13!4m12!1m0!1m5!1m1!1s0x4871444acb184f47:0x4494aad55da7164!2m2!1d-1.7708572!2d51.5632739!3e0!6m3!1i0!2i0!3i1) and elsewhere.)

The MUTCD, the standard for road markings in the U.S., includes the following [definitions](https://mutcd.fhwa.dot.gov/htm/2009/part1/part1a.htm#section1A13):

> 30. Circular Intersection—an intersection that has an island, generally circular in design, located in the center of the intersection where traffic passes to the right of the island. Circular intersections include roundabouts, rotaries, and traffic circles.
> <div></div>
> 
> 180. [Roundabout](https://mutcd.fhwa.dot.gov/htm/2009/part3/part3c.htm)—a circular intersection with yield control at entry, which permits a vehicle on the circulatory roadway to proceed, and with deflection of the approaching vehicle counter-clockwise around a central island.

As of the 2009 edition, which was the first edition to specify various details about roundabouts, either word may be used on signage, but “roundabout” is preferred:

![plaque](http://slideplayer.com/slide/8479559/26/images/26/New+Roundabout+plaque+for+circular+intersection+warning.jpg)

/cc @mcwhittemore @danpat

**Comment by 1ec5** [comment]
> We don’t want to have to maintain separate `en-GB`, `en-AU`, `en-NZ`, etc. localizations just for this one word (although I wouldn’t be opposed to starting more localizations for other reasons).

The U.S. is the odd one out in terms of using “traffic circle” to any extent, so we could create an `en-US` localization that says “traffic circle” and revert `en` to say “roundabout” for all the other English-speaking countries.

**Comment by 1ec5** [comment]
Rather amusingly, some languages have replaced their translations of “roundabout” with literal translations of “traffic circle”, such as Esperanto:

https://github.com/Project-OSRM/osrm-text-instructions/blob/c3b3ab63e9b1894c63664480773c2340660fc5bf/languages/translations/eo.json#L391

This is a made-up word that no one uses, but the English localization’s idiosyncratic use of “traffic circle” is dissuading other localizations from using the correct terms for roundabout.

**Comment by 1ec5** [comment]
Some additional data points:

* “Traffic circle” used to be a somewhat more common term than “roundabout” in the U.S., as seen [in the 2003 Harvard Dialect Survey](https://www4.uwm.edu/FLL/linguistics/dialect/staticmaps/q_84.html) ([interactive version](http://www.tekstlab.uio.no/cambridge_survey/maps/324), [background](http://languagelog.ldc.upenn.edu/nll/?p=4676)).
* The 2007 successor to that survey, the Cambridge Online Survey of World Englishes, shows [a decisive shift in favor of “roundabout”](http://www.tekstlab.uio.no/cambridge_survey/maps/70). This correlates to the rise of modern roundabouts in the United States.
* The ongoing [Dialects of American English survey](https://www.dialectsofenglish.com/) ([background](http://languagelog.ldc.upenn.edu/nll/?p=37429)) that began earlier this year currently shows that “[traffic circle](https://www.dialectsofenglish.com/static/heatmaps/heatmap-21-4.png)” is confined to the Mid-Atlantic states, while use of “[roundabout](https://www.dialectsofenglish.com/static/heatmaps/heatmap-21-2.png)” is widespread. (All three surveys have an “I have no word for this” option, which probably mitigates the impact of “roundabout”’s international usage.)
* In absolute terms, [most roundabouts](https://www.citi.io/2016/03/15/why-america-may-wrongly-hate-those-roundabouts/) in the U.S. are located in regions where people call them “roundabouts”.

**Comment by kiskunk** [comment]
I would like to see the return of Roundabout instead of traffic circle

**Comment by andrewharvey** [comment]
I was just about to submit a PR implementing an `en-au` replacing `traffic circle` with `roundabout`. At least here everyone says roundabout, I've never heard traffic circle before.

I couldn't see anything else that should be changed, so @1ec5 is there a decision on if we should have a separate `en-au` and others, or just change `en` to roundabout?

I don't mind either option, certainly just changing `en` is simplest but certainly don't want the US to feel forced into using a less than perfect name.
