### ISSUE TITLE
Make instructions.json format localizable

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#19]
For the instructions strings file, we should use a format that standard localization tools can work with. What we have now is more or less the [JSON key-value format](http://docs.transifex.com/formats/json/) supported by Transifex, but with an informal mini-language around placeholders and optional clauses. This format has some downsides for localization:
1. No way to provide comments to localizers
   - Switching to [Chrome JSON](http://docs.transifex.com/formats/chrome_json/) format would address this issue.
2. No way to vary capitalization or word order when a clause is omitted
   - We should get rid of all `[optional]` clauses and enumerate all the possibilities. String concatenation always works against localizability.
3. No way to vary surrounding words based on a placeholder’s number or grammatical gender
   - We could build this ourselves by allowing any string to be replaced by an object mapping number patterns (`ONE`, `TWO`, `MANY`) to message variants, but localizers would be unable to add their own variants using a tool like Transifex.

Primarily for (3) and so that other clients don’t have to build their own custom parsers, we should consider switching to one of the [other Transifex formats](http://docs.transifex.com/formats/) that happens to support these features. As an iOS developer, I’m most familiar with [.strings](http://docs.transifex.com/formats/apple-strings/) and .stringsdict, but [gettext](http://docs.transifex.com/formats/gettext/) and [XLIFF](http://docs.transifex.com/formats/xliff/) are solid formats that support all the features we need for localization while being compatible [with Node](https://www.npmjs.com/package/grunt-xliff), [Android](https://developer.android.com/distribute/tools/localization-checklist.html), and [iOS](https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html) development.

Depends on #6 and #5.

/cc @bsudekum @MoKob @freenerd @zugaldia

**Comment by freenerd** [comment]
After #27 this is were we are at:

> 1. No way to provide comments to localizers

This is not there yet, using [chrome json](http://docs.transifex.com/formats/chrome_json/) as suggested feels like a good idea. Need to do a sample implementation of that.

> 2. No way to vary capitalization or word order when a clause is omitted
> We should get rid of all [optional] clauses and enumerate all the possibilities. String concatenation always works against localizability.

We have no optional clauses anymore, everything is spelled out completely in whole strings. We still have string interpolation via `{token}`.

> 3. No way to vary surrounding words based on a placeholder’s number

I don't think we actually have a counting problem in instructions right now. We have ordinalization, which is included.

> 3. No way to vary surrounding words based on [..] grammatical gender

We do not have grammatical gender support. Translating to german (which is gender-aware) might be a good test

Next:

- [ ] Test Chrome JSON
- [ ] Get trans

**Comment by freenerd** [comment]
We have a couple of languages in now and that seemed fine. Closing until we run into problems again (comments, counting, gender)
