### ISSUE TITLE
Omit exit side when it's the same as driving side

### ISSUE THREAD

**Issue by lyzidiamond** [Project-OSRM/osrm-text-instructions#198]
Exit instructions should omit the exit side unless it is different from the driving side.

Currently (in the US, where `driving_side === 'right'`: "Take exit 5 on the right towards Main Street"
After this change: "Take exit 5 towards Main Street"
Currently: "Take exit 7 on the left towards First Ave"
After this change: "Take exit 7 on the left towards First Ave"

@1ec5 @hdaymon @mcwhittemore @allierowan @coxchapman

**Comment by 1ec5** [comment]
We previously attempted to remove the exit side unconditionally in #124 but rolled it back in in #125 due to adverse effects on wrong-sided exits. #199 once again removes the exit side, except for on wrong-sided exits.

**Comment by lyzidiamond** [comment]
Closed in #199!
