### ISSUE TITLE
Remove "at the fork" from forks

### ISSUE THREAD

**Issue by lyzidiamond** [Project-OSRM/osrm-text-instructions#202]
## Summary

Current behavior: "Keep right at the fork towards Foster Road."
Desired behavior: "Keep right towards Foster Road."

Right now, the words "at the fork" appear in every `fork` instruction. I propose that we remove "at the fork" from these instructions. Why?
  - it doesn't add additional context that you can't get from looking at the road
  - it makes voice instructions longer

All "fork" instructions can be seen here: https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/en.json#L157-L188

## Acceptance criteria / implementation plan

Remove "at the fork" from every `fork` instruction.

@allierowan @hdaymon @mcwhittemore

**Comment by brianolsen87** [comment]
I would be in favor of keeping "at the fork" myself. If the fork is too far to see or is blocked by traffic it may be useful context for the user to know if they can't look at the application.
