### ISSUE TITLE
How can I use this to set the lang to leaflet-routing-machine?

### ISSUE THREAD

**Issue by fagworio** [Project-OSRM/osrm-text-instructions#249]
How can I set the lang to 'pt-BR' using osrm-text-instructions to  leaflet-routing-machine?
Someone has a sample to share how to do this.

```    L.Routing.control({
                waypoints: [
                    L.latLng(57.74, 11.94),
                    L.latLng(57.6792, 11.949)
                ],
                language: 'pt-BR',
            }).addTo(map);
```
 Thanks.

**Comment by yuryleb** [comment]
This is the question mostly to [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine), isn't it? :wink:

**Comment by fagworio** [comment]
Sorry, I will change the topic to  leaflet-routing-machine.
