### ISSUE TITLE
Remove number-to-words js module

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#25]
We are using [number-to-words](https://github.com/marlun78/number-to-words). I think we'd want to remove the dependency completely:

- we need to own all translation strings ourselves
- the module won't be available in other programming environments than javascript

**Comment by 1ec5** [comment]
We should have non-JavaScript environments be responsible for filling in already wordified numbers. The JS reference implementation in this repository could then continue to use number-to-words to wordify a number before filling it into the format strings provided by the JSON.

**Comment by freenerd** [comment]
@1ec5 you mean `number-to-words` would generate the JSON lookup table in english?

Given that we currently only use this for counting roundabout exits and maybe in the future crossing intersections, we are probably fine to limit the numbers we want to support to something like 10 or 20. In that case one self-maintained lookup feels easiest to me.

**Comment by freenerd** [comment]
Done in #27 

Counting to 10 only for now
