### ISSUE TITLE
"Take the ramp" can be either an enter or an exit

### ISSUE THREAD

**Issue by kiskunk** [Project-OSRM/osrm-text-instructions#272]
In other languages than English Take the ramp cannot be translated to fit all possibilities, it should be separated into enter-ramp exit-ramp.

**Comment by 1ec5** [comment]
This is the difference between `on ramp` and `off ramp` in the translation files. In Transifex, you can see whether the message is used for `on ramp` or `off ramp` in Context tab, under “Key”.
