### ISSUE TITLE
Extra `à` in french waypoint_name arrival instruction

### ISSUE THREAD

**Issue by danpaz** [Project-OSRM/osrm-text-instructions#275]
I noticed a typo in the french localization of the `arrive.right.named` maneuver instruction:

https://github.com/Project-OSRM/osrm-text-instructions/blob/9de8ca2e5c9a6071b704bd302fca9a293de73365/languages/translations/fr.json#L80

There appears to be an extra `à` and whitespace. These should be removed, and the [fixtures](https://github.com/Project-OSRM/osrm-text-instructions/blob/9de8ca2e5c9a6071b704bd302fca9a293de73365/test/fixtures/v5/arrive_waypoint_name/right.json#L18) should be regenerated.

**Comment by yuryleb** [comment]
Is it in Transifex translation?

**Comment by 1ec5** [comment]
The JSON translation file reflects what’s in Transifex, yes. The extra “à” is added by this grammar rule:

https://github.com/Project-OSRM/osrm-text-instructions/blob/9de8ca2e5c9a6071b704bd302fca9a293de73365/languages/grammar/fr.json#L184

So should the grammar rule or the translation be responsible for adding “à”?
