### ISSUE TITLE
Add destination information to ramp types

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-text-instructions#28]
Where a destination is provided, it should be used in place of name for ramps.

/cc @freenerd

**Comment by freenerd** [comment]
This should already be the case, with `destination` taking precendence over `name` strings in general https://github.com/Project-OSRM/osrm-text-instructions/pull/27/files#diff-168726dbe96b3ce427e7fedce31bb0bcR93

**Comment by freenerd** [comment]
Fixed in #27
