### ISSUE TITLE
Directions images

### ISSUE THREAD

**Issue by joaotomaspinheiro** [Project-OSRM/osrm-text-instructions#300]
Hi!
I have a question.
When requesting the text directions, it returns all the text instructions by steps to take in the route. Is it possible to have the corresponding images of the directions, for example, turn right or continue straight?
Like this:
![577231-200](https://user-images.githubusercontent.com/60696790/96016359-8e1ea180-0e40-11eb-8d7f-c3d272a82de3.png)
![images](https://user-images.githubusercontent.com/60696790/96016382-94148280-0e40-11eb-9c08-3fd351f172a9.png)

Or does the images have to be added manually? 
And if so, how do I do it?

**Comment by yuryleb** [comment]
Please look how frontend does this starting from this line: https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/itinerary_builder.js#L44
