### ISSUE TITLE
i can't understand about french grammar [help]

### ISSUE THREAD

**Issue by MohsenHaydari** [Project-OSRM/osrm-text-instructions#308]
Hi,
when I use normal translation to translate navigation instruction for French give me some result like 
```
Place de l'Hôtel de Ville

```
but with grammar, I got results like 
```
la place de $1'Hôtel de Vill

```
what is `$1`? Thanks

**Comment by 1ec5** [comment]
That’s unexpected. You should be seeing the “l’” article come through untouched. Are you using the usual `compile()` function, and are you using any options such as `formatToken`?

I think the `$1` is coming from the following line in the French “grammar” file:

https://github.com/Project-OSRM/osrm-text-instructions/blob/6a77ef9be61b6f3b659177b47e407ccb87b63975/languages/grammar/fr.json#L58

The following code is supposed to replace the `$1` on the right side with the “d” or “l” captured in the left side:

https://github.com/Project-OSRM/osrm-text-instructions/blob/6a77ef9be61b6f3b659177b47e407ccb87b63975/index.js#L254-L260

**Comment by MohsenHaydari** [comment]
> That’s unexpected. You should be seeing the “l’” article come through untouched. Are you using the usual `compile()` function, and are you using any options such as `formatToken`?
> 
> I think the `$1` is coming from the following line in the French “grammar” file:
> 
> https://github.com/Project-OSRM/osrm-text-instructions/blob/6a77ef9be61b6f3b659177b47e407ccb87b63975/languages/grammar/fr.json#L58
> 
> The following code is supposed to replace the `$1` on the right side with the “d” or “l” captured in the left side:
> 
> https://github.com/Project-OSRM/osrm-text-instructions/blob/6a77ef9be61b6f3b659177b47e407ccb87b63975/index.js#L254-L260
Hi, thanks for your answer, I use dart language for this my tokenize method
```
if (grammers != null) {
      final out = output.replaceAllMapped(
        RegExp(
          r"\{(\w+)(?::(\w+))?\}",
          caseSensitive: false,
        ),
        (match) {
          final String? token = match[0];
          String? tag = match[1];
          String? grm = match[2];
          String? value = tokens[tag];
          if (value == null) {
            return token!;
          }
          value = grammerReplace(value, grm, grammers);
          return value;
        },
      ).replaceAll(RegExp(r' {2}'), ' ');
      return RoadHelper(out, icon);
    }else{
   tokens.forEach((key, value) {
      output = output.replaceAll('{$key}', value);
    });
}

```
grammerReplace

```
static String grammerReplace(String name, String? grammar, Map<String, dynamic> grammers) {
    if (grammar == null) return name;
    List<dynamic>? rules = grammers["v5"]?[grammar];
    if (rules == null) return name;
    String n = ' $name ';
    for (var rule in rules) {
      RegExp re = RegExp("${rule[0]}", unicode: true, caseSensitive: true);
      n = n.replaceAll(re, rule[1]);
    }
    return n.trim();
  }

```

**Comment by 1ec5** [comment]
Ah, I didn’t realize you were using the grammar data in a port of this library. There’s actually a spot in the readme for promoting ports, in case you’re interested. 🙂

https://github.com/Project-OSRM/osrm-text-instructions/blob/6a77ef9be61b6f3b659177b47e407ccb87b63975/README.md#L9

> ```dart
> n = n.replaceAll(re, rule[1]);
> ```

According to the [`replaceAll`](https://api.dart.dev/stable/3.0.2/dart-core/String/replaceAll.html) documentation, you’ll need to use [`replaceAllMapped`](https://api.dart.dev/stable/3.0.2/dart-core/String/replaceAllMapped.html), which understands the `$n` syntax.
