### ISSUE TITLE
Create Catalan translation 

### ISSUE THREAD

**Issue by yopaseopor** [Project-OSRM/osrm-text-instructions#310]
Hi!
Catalan translation is done in Transifex so, can you create that?

**Comment by 1ec5** [comment]
I included Catalan in a belated omnibus update: #312. Can you take a look at the last commit in that PR – the one adding Catalan – and double-check that the generated sample phrases make sense? Thanks!

**Comment by yopaseopor** [comment]
Thank you for including Catalan. Now I'm reviewing translations because Transifex did not allow me to do that. Some sentences are completed with the original phrase in English.

**Comment by yopaseopor** [comment]
Transifex translations reviewed and corrected. How can I review the other sentences outside of Transifex?

**Comment by 1ec5** [comment]
Do you need access to the Transifex project to make corrections? I can add you as a translator for Catalan, if you aren’t already a member of the translation team there.
