### ISSUE TITLE
Omit redundant lane information

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#42]
"Keep left to turn left" is redundant. We should only indicate lanes when they contradict the user's intuition, like for Melbourne-style left-lane right turns.

/cc @freenerd @bsudekum

**Comment by willwhite** [comment]
Do we still do this? Is there an example route?

**Comment by 1ec5** [comment]
This issue was filed in response to a prototype implementation that tacked lane guidance onto every instruction. In #38, we took the more conservative approach of including lane guidance only in `use lane` instructions and opened #48 as tail work to incorporate it into other kinds of instructions. As I understand it, `use lane` is going away, making #48 more important. Let’s track the remaining work there.
