### ISSUE TITLE
Allow for translations

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-text-instructions#5]
We could probably move `instructions.json` to a language folder, then have different json files for each language.

**Comment by freenerd** [comment]
To make this work  we need to be sure to have all language strings in json, not code  https://github.com/Project-OSRM/osrm-text-instructions.js/issues/6

**Comment by freenerd** [comment]
This has landed with https://github.com/Project-OSRM/osrm-text-instructions/pull/58
