### ISSUE TITLE
Sometimes use only name or ref, not both

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#51]
There are cases where it would be better to ignore the `name` and only use the `ref`

<img width="733" alt="screen shot 2016-10-20 at 19 00 43" src="https://cloud.githubusercontent.com/assets/25713/19584188/851e12ba-96f7-11e6-98ea-659c8761ec88.png">

http://map.project-osrm.org/?z=15&center=38.868532%2C-77.056947&loc=38.877670%2C-77.040553&loc=38.868248%2C-77.048450&hl=en&alt=0

There are cases where it would be better to ignore the `ref` and only use the `name`

<img width="655" alt="screen shot 2016-10-20 at 19 02 17" src="https://cloud.githubusercontent.com/assets/25713/19584228/bce0a636-96f7-11e6-9a63-b0265691dcb3.png">

http://map.project-osrm.org/?z=16&center=52.518304%2C13.445184&loc=52.517331%2C13.453681&loc=52.522501%2C13.450441&hl=en&alt=0

Doing this is a hard problem, since it requires local knowledge. I do not know how we'd solve this.

**Comment by 1ec5** [comment]
There are multiple parts to this problem:

* Following a route often means traversing a series of roads with different names. #41 would introduce more contextually appropriate phrasing such as “Keep right at the fork to stay on B 96a” in the event that the previous and current steps share the ref in common.
* The George Mason Memorial Bridge example above is a special case in which “stay on” phrasing would leave us with a useless instruction: “Stay on I-395”. OSRM would ideally elide such instructions altogether.
* In some jurisdictions, or for some route networks, or for some particular roads, the ref may be more important than the name or vice versa.

This last part is the most intractable, as it requires local knowledge. For example, in some jurisdictions, a freeway’s name may not even be posted prominently enough for use in navigation. The road would be solely identified by a route shield, optionally with destinations:

![norwood-lateral](https://cloud.githubusercontent.com/assets/1231218/19593417/59dae040-9735-11e6-8070-02ee7cc0743a.jpg)

You might only see the name after driving on the road for several miles:

![](http://www.sanduskyregister.com/image/2016/06/29/x700_q30/Road-Trip-GAR-06282016.jpg)

Or only after stopping at a rest area or roadside attraction:

![](http://www.sanduskyregister.com/image/2016/06/30/x700_q30/Road-Trip-GAR-06292016.jpg)

On the other hand, there are plenty of expressways and surface streets that are primarily identified by name, even if they have route designations:

![lawrence-expressway](https://cloud.githubusercontent.com/assets/1231218/19593475/9f6a772e-9735-11e6-9371-8bd3c4eaf318.jpg)

Lawrence Expy. (shown above) does have a few route shields posted, but a non-local would never be able to navigate using them:

![g2](https://cloud.githubusercontent.com/assets/1231218/19593588/2eb1f83a-9736-11e6-97a7-b18043d7f39e.jpg)

In OpenStreetMap, it’s fairly common to use tags such as `official_name` for road names that only appear in government documents, or for honorary names that appear alongside more common names in signage, as well as `loc_name` for road names that are only used by locals and never signposted. However, there’s no standard way to indicate that a name is in widespread use but not signposted consistently enough for navigation.

We could develop heuristics like preferring refs for motorways and names for everything else, but there are too many cases we’d get wrong. I think using contextual clues to omit a name or ref is probably the best way forward on this issue.

**Comment by bsudekum** [comment]
> I think using contextual clues to omit a name or ref is probably the best way forward on this issue.

@1ec5 how can we begin to do this?

**Comment by 1ec5** [comment]
>> I think using contextual clues to omit a name or ref is probably the best way forward on this issue.

> @1ec5 how can we begin to do this?

#41 and Project-OSRM/osrm-backend#3281 are the next steps.

Beyond that:

> We could develop heuristics like preferring refs for motorways and names for everything else

However, OSRM doesn't tell us the classification of each road. So we'd have to base this determination on either:

* The speed limit (expected distance divided by expected duration). But this won't work when ETAs account for traffic.
* The network code in the ref, but this is specific to OSM and also won't scale. An application could decide to treat `ref: I *` as motorway, but that isn't for osrm-text-instructions to decide.

**Comment by freenerd** [comment]
I believe https://github.com/Project-OSRM/osrm-text-instructions/issues/30 could be a cheap next step to mitigate some of these problems. It would check all `ref` and `name` of the steps of the route and decide for each one which to use, based on the weight that they get.

**Comment by willwhite** [comment]
Tracking on https://github.com/Project-OSRM/osrm-text-instructions/issues/133 now.
