### ISSUE TITLE
Callback for token replacement values in compile

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions#52]
https://github.com/Project-OSRM/osrm-text-instructions/pull/47 feels brittle, since it depends on the format of the `instructions.json` and therefore couples code tightly.

Instead, @1ec5 proposed to introduce a hook [just before the final token replacement](https://github.com/Project-OSRM/osrm-text-instructions/blob/4d2428224f1835394f21018ccd47219c1f2ae6c9/index.js#L153). That would be a more-stable API, while allowing even more functionality.

**Comment by 1ec5** [comment]
Not sure why this was closed. We implemented [a callback](https://github.com/Project-OSRM/osrm-text-instructions.swift/blob/b48a5a072168edd53680c5cb3d86934ef8df9e11/OSRMTextInstructions/OSRMTextInstructions.swift#L179) parameter in the Swift port, and it’s been quite helpful for [marking up the resulting string in SSML](https://github.com/mapbox/mapbox-navigation-ios/blob/b33f7f619305edf1902409dc8629fe734d1f234b/MapboxCoreNavigation/RouteStepFormatter.swift#L24-L35).

**Comment by 1ec5** [comment]
The `token()` function would stay as-is, but the `compile()` function would accept an additional `interpolator` function that takes a `tokenType` and `rawValue` and returns a string (typically based on `rawValue`).

**Comment by 1ec5** [comment]
If a client wishes to mark up parts of a road name, such as surrounding numbers in an SSML tag as in mapbox/mapbox-navigation-ios#552, then the current approach would be:

1. `way_name` comes from OSRM.
1. The client marks up `way_name` in place.
1. The marked-up `way_name` is passed into `compile()`.
1. The marked-up `way_name` is inserted into the instruction string.

Per https://github.com/Project-OSRM/osrm-text-instructions/pull/102#discussion_r141936188, this approach is too fragile for our needs. This library loses access to the original `way_name`, which is needed for declension logic. The proper order of operations would be:

1. `way_name` comes from OSRM and is passed to `compile()` as-is.
2. `way_name` is declined via the logic in #102.
3. The client is given an opportunity to mark up the declined `way_name` via the callback proposed in this issue.
4. The declined, marked-up `way_name` is finally inserted into the instruction string.

/cc @allierowan @yuryleb
