### ISSUE TITLE
Merge slightly/sharply left/right should be merge left/right

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions#57]
There are instructions like “[Merge slightly left towards {destination}](https://github.com/Project-OSRM/osrm-text-instructions/blob/59620dd9f7da5bc1ab646d4174f82e8ca0354626/instructions.json#L162)”. Adverbs like “slightly and sharply” should be removed from merge instructions.

One does not merge “slightly” or “sharply” to the left or right. When you say “merge left”, “left” indicates which side the other traffic is coming from, not which way you’ll turn, so there’s no distinction between slight, normal, and sharp.

/cc @freenerd @bsudekum

**Comment by freenerd** [comment]
Fixed in https://github.com/Project-OSRM/osrm-text-instructions/pull/67
