### ISSUE TITLE
handle waypoints

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-text-instructions#7]
ref https://github.com/Project-OSRM/osrm-text-instructions/blob/f1d966c1589926e84f36c79e6d62682f3d8510ea/index.js#L38

**Comment by freenerd** [comment]
Reason for implementing this is that we used to issue the following `arrive` instructions, in cases of multiple legs on a route.

- `You have arrived at your second destination, on the right`
- `You have arrived at your final destination, on the right`

I don't feel that counting strongly that this is a useful feature. I think instead the implementing application needs to figure out, how several legs are displayed to the outside of text instructions.

**Comment by 1ec5** [comment]
Fixed in #111.
