### ISSUE TITLE
Never allow english strings outside of instructions.json

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-text-instructions#8]
Can we lint for this?

/cc @freenerd

**Comment by bsudekum** [comment]
First step was done in https://github.com/Project-OSRM/osrm-text-instructions/pull/20

Next, rotary logic needs to have a few english phrases removed

**Comment by freenerd** [comment]
I think #27 should have fixed this completely, everything is in instructions.json.
