### ISSUE TITLE
Improve lane instruction

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-text-instructions#91]
Currently:

```
Keep in the middle
```

Should be:
```
Use the middle lane
```

/cc @pveugen

**Comment by freenerd** [comment]
Adding that we should pluralize this correctly as well:

- `oxxo` => Use the middle lanes
- `oxo` => Use the middle lane

**Comment by hdaymon** [comment]
This instruction does not exist anymore. #48 is a better description of where we are going.
