### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by josek5494** [Project-OSRM/osrm-text-instructions#93]
I have some instructions translated if it helps: http://www.filedropper.com/spanishtranslation_1 It would be very nice if you could implement it! Thanks and great work!

**Comment by 1ec5** [comment]
Hi @josek5494, this project’s translations are managed at Transifex. Once you [join the Spanish translation team](https://www.transifex.com/project-osrm/osrm-text-instructions/language/es/), you can add or import translations there, and we’ll periodically pull in the translations for all languages into this repository. Thanks!

**Comment by josek5494** [comment]
Ok nice, maybe i'll join with a friend to translate. Thank you!
